Added failure tests

diff --git a/.github/workflows/numba-python-compatibility-actions.yml b/.github/workflows/numba-python-compatibility-actions.yml
--- a/.github/workflows/numba-python-compatibility-actions.yml
+++ b/.github/workflows/numba-python-compatibility-actions.yml
@@ -24,12 +24,23 @@ jobs:
         with:
           repository: TDAmeritrade/stumpy
       - name: Install STUMPY And Other Dependencies
-        run: python -m pip install --editable .[ci] || true
+        run: python -m pip install --editable .[ci] 2> stderr.text || true
         shell: bash
+      - name: Check installation
+        run: |
+          if [[ `grep RuntimeError stderr.txt | wc -l` gt "0" ]]; then \
+            echo "Installation Failed"
+            exit 0
+          else
+            echo "Installation Succeeded"
+            exit 1
+          fi
       - name: Run STUMPY Unit Tests
+        if: failure()
         run: ./test.sh unit
         shell: bash
       - name: Create New STUMPY Issue Using REST API
+        if: failure()
         run: |
           curl --request POST \
           --url https://api.github.com/repos/TDAmeritrade/stumpy/issues \
