Removed backslashes

diff --git a/.github/workflows/numba-python-compatibility-actions.yml b/.github/workflows/numba-python-compatibility-actions.yml
--- a/.github/workflows/numba-python-compatibility-actions.yml
+++ b/.github/workflows/numba-python-compatibility-actions.yml
@@ -28,12 +28,12 @@ jobs:
         shell: bash
       - name: Check installation
         run: |
-          if [[ `grep RuntimeError stderr.txt | wc -l` -gt "0" ]]; then \
-            echo "Installation Failed" \
-            exit 0 \
-          else \
-            echo "Installation Succeeded" \
-            exit 1 \
+          if [[ `grep RuntimeError stderr.txt | wc -l` -gt "0" ]]; then
+            echo "Installation Failed"
+            exit 0
+          else
+            echo "Installation Succeeded"
+            exit 1
           fi
       - name: Run STUMPY Unit Tests
         if: failure()
